import { Card } from '@/components/Card'
import { Footer } from '@/components/Footer'
import { Navbar } from '@/components/Navbar'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'


export default function Home() {
const router = useRouter()
return (
<>
<Head>
<title>Gracious Crossing</title>
<meta name="description" content="Generated by create next app" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="icon" href="/favicon.ico" />
</Head>
   
<Navbar/>      
           

<section className="hero">
<h1>Welcome to Gracious Crossing </h1>
<p>Here you can find all the information you need about our products and services.</p>
<Link href="/services" className="herobtn">Go To Services</Link>
  

</section>  

     <Card/> 
     <Footer/>
</>
)
}
