import React from 'react'
import { useRouter } from 'next/router'
import Image from 'next/image'
import { Navbar } from '@/components/Navbar'
import { Footer } from '@/components/Footer'
import neighbor from "../pages/img/bg-service-neighnorhood.jpg"
import valueation from "../pages/img/bg-service-valuation.jpg"
import servicetours from "../pages/img/bg-service-tours.jpg"
import homeguide from "../pages/img/bg-home-guide.png"
import Head from 'next/head'
const Services = () => {
return (
<>
<Head>
<title>Gracious Crossing | Services</title>
<meta name="description" content="Generated by create next app" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="icon" href="/favicon.ico" />
</Head>
<Navbar/>
<div className="container">
<h1 style={{textAlign:'center'}}>Our Services</h1>
<div className="service">
<Image src={homeguide} alt="Service 5" width={500} height={333} priority/>
<h3>Home Buying Guide</h3>
<p>Our team of experts has put together a comprehensive guide to help you navigate the home buying process. Our guide covers everything from choosing the right neighborhood to negotiating with sellers.</p>
<ul>
<li>Step-by-step guide to the home buying process</li>
<li>Tips for choosing the right neighborhood</li>
<li>Advice on financing options</li>
          <li>Negotiation strategies for getting the best deal</li>
</ul>
<p>Our team is also available to answer any questions you may have about the home buying process.</p>
</div>
<div className="service">
<Image src={servicetours} alt="Service 6" width={500} height={333} priority/>
<h3>Virtual Tours</h3>
<p>We understand that visiting properties in person may not always be possible. That's why we offer virtual tours of our properties, allowing you to explore homes from the comfort of your own home.</p>
<ul>
<li>High-quality 360-degree virtual tours</li>
<li>Option to schedule a live virtual tour with a real estate agent</li>
<li>Ability to ask questions and get real-time answers during live virtual tours</li>
</ul>
<p>Our virtual tours are a convenient and safe way to explore homes before making a decision.</p>
</div>

<div className="service">
<Image src={valueation} alt="Service 7" width={500} height={333}  priority/>
<h3>Home Valuation</h3>
<p>If you're thinking of selling your home, our team can provide you with a free home valuation. We use data and analytics to determine the fair market value of your home, giving you an accurate estimate of its worth.</p>
<ul>
<li>Free home valuation</li>
<li>Accurate estimate of your home's worth</li>
<li>Insight into market trends and conditions</li>
</ul>
<p>Our team can help you determine the best price for your home, allowing you to sell quickly and for the highest possible price.</p>
</div>

<div className="service">
<Image src={neighbor} alt="Service 8" width={500} height={333} priority/>
<h3>Neighborhood Insights</h3>
<p>Choosing the right neighborhood is just as important as finding the right home. That's why we provide insights and information about the neighborhoods where our properties are located.</p>
<ul>
<li>Demographic data about the neighborhood</li>
<li>Information about schools, parks, and other amenities</li>
<li>Insight into local real estate trends and conditions</li>
</ul>
<p>Our neighborhood insights can help you make an informed decision about where to buy your next home.</p>
</div>




    </div>
<Footer/>
</>
)
}

export default Services